# Generated by Django 2.2 on 2019-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='add_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
