# Generated by Django 2.2 on 2019-04-25 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190423_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
